Modify Time
Kayzels/Pomodoro pull request #1
Opened 2023-05-25 15:55 UTC by John-JonSteyn

+ Add increase and Decrease buttons.
+ Expand README.
+ Add LICENSE.

2023-05-25 17:27 UTC, Kayzels requested changes
Due to using PyQt, it can't be MIT license. It requires it to be GPL.

Thanks for pointing out I forgot to add a License.

2023-05-25 18:02 UTC, Kayzels commented
I'll need to go through more carefully. Some comments that you deleted seemed useful, and should remain. It makes it easier to see the reasoning.

Thank you for your pull request.

2023-05-26 08:49 UTC, Kayzels requested changes

2023-05-26 08:49 UTC, Kayzels commented on main.py
> +            0: ("Long Break", LONG_BREAK_MIN, "#80c342"),
Not sure about these changes. Not a fan of random tuples.I agree the original code could be neatened, though. A data lass might be useful.

Also dictionaries that operate as a list also bother me.

2023-05-26 08:49 UTC, Kayzels commented on main.py
> -
The blank lines here are not redundant. They're there deliberately to break the code in the init into it's logical portions. It makes it easier to follow when skimming.

Call super
Connect button signals to slots
Set timer settings
Set defaults

2023-05-26 08:49 UTC, Kayzels commented on main.py
> +        super().__init__(*args, **kwargs)
This change works, happy here

2023-05-26 08:49 UTC, Kayzels commented on main.py
> +        mins, secs = divmod(self.timeRemainingSec, 60)
Did not know about this function, thank you. Agree with this change.

2023-05-26 08:49 UTC, Kayzels commented on main.py
> +    sys.exit(app.exec())
Happy with this change as well

2023-05-26 08:49 UTC, Kayzels commented on main.py
> +        self.workTimer.setInterval(1000)
The comment here is useful, because it is not immediately clear that the function works in milliseconds.

2023-05-26 15:50 UTC, Thorin-the-Bearded commented on main.py
> +            0: ("Long Break", LONG_BREAK_MIN, "#80c342"),
Not sure how to do a data lass, but I can find out tomorrow.    : 3

2023-05-27 05:18 UTC, Thorin-the-Bearded commented on main.py
> +            0: ("Long Break", LONG_BREAK_MIN, "#80c342"),
Oh. Class. XD!

2025-01-20 07:46 UTC, closed without merging

2025-01-20 07:52 UTC, Kayzels commented
Sorry for closing this, and not doing more with it. And for taking so long to get back to you.

Unfortunately, this request makes too many changes, so I would need to cherry pick and go through to select the ones I want. This seems to be more effort than it's worth, for a project that I haven't used in years. It also appears that you have a main branch in your fork with an updated version that does make changes such as correcting the license, but there wasn't a pull request from that branch.